service: aws-lambda-node
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:845068608633:table/tasksTable

functions:
  api:
    handler: src/hello.handler
    events:
      - httpApi:
          path: /
          method: get
  createTask:
    handler: src/addTask.addTask
    events:
      - httpApi:
          path: /task
          method: POST
  getTasks:
    handler: src/getTasks.getTasks
    events:
      - httpApi:
          path: /task
          method: GET
  getTask:
    handler: src/getTask.getTask
    events:
      - httpApi:
          path: /task/{id}
          method: GET
  updateTask:
    handler: src/updateTask.updateTask
    events:
      - httpApi:
          path: /task/{id}
          method: PUT
  deleteTask:
    handler: src/deleteTask.deleteTask
    events:
      - httpApi:
          path: /task/{id}
          method: DELETE

resources:
  Resources:
    tasksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tasksTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
